# Generated by Django 5.2.17 on 2026-09-02 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("STOCK_BAJO", "Stock bajo de materia prima"),
                            ("NUEVO_PEDIDO", "Nuevo pedido"),
                            ("PEDIDO_ASIGNADO", "Pedido asignado"),
                            ("ESTADO_PEDIDO", "Cambio de estado de pedido"),
                            ("PRODUCCION_PROGRAMADA", "Producción programada próxima"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("mensaje", models.TextField()),
                ("leida", models.BooleanField(default=False)),
                ("referencia_id", models.PositiveIntegerField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
