# Generated by Django 5.2.17 on 2026-09-02 16:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[("LB", "Libras"), ("OZ", "Onzas")], max_length=2
                    ),
                ),
                (
                    "stock_actual",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lote", models.CharField(max_length=100)),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[("LB", "Libras"), ("OZ", "Onzas")], max_length=2
                    ),
                ),
                (
                    "cantidad_nativa",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "cantidad_restante",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("costo_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                ("fecha_compra", models.DateField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="materia_prima.materiaprima",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_compra", "creado_en"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventarioMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra"),
                            ("PRODUCCION", "Consumo en producción"),
                            ("MERMA", "Merma"),
                            ("AJUSTE", "Ajuste autorizado"),
                        ],
                        max_length=12,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                ("motivo", models.CharField(max_length=255)),
                (
                    "saldo_resultante",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "compra",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote específico afectado (compra, consumo o merma). Nulo en ajustes.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="materia_prima.compra",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_materia_prima",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="materia_prima.materiaprima",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en", "-id"],
            },
        ),
    ]
