# Generated by Django 5.2.17 on 2026-09-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SincronizacionOdoo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("VENTA", "Venta"), ("COMPRA", "Compra")],
                        max_length=10,
                    ),
                ),
                ("referencia_id", models.PositiveIntegerField()),
                ("odoo_id", models.PositiveIntegerField(blank=True, null=True)),
                ("sincronizado_en", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creado_en"],
                "unique_together": {("tipo", "referencia_id")},
            },
        ),
    ]
