# Generated by Django 5.2.17 on 2026-09-02 17:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materia_prima", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stock_actual",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Produccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "cantidad_planificada",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "cantidad_producida",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "cantidad_merma",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producciones",
                        to="produccion.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ConsumoMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[("LB", "Libras"), ("OZ", "Onzas")], max_length=2
                    ),
                ),
                (
                    "costo_correspondiente",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="materia_prima.materiaprima",
                    ),
                ),
                (
                    "movimientos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="consumos_produccion",
                        to="materia_prima.movimientoinventariomateriaprima",
                    ),
                ),
                (
                    "produccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumos",
                        to="produccion.produccion",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventarioProductoTerminado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRODUCCION", "Entrada por producción"),
                            ("VENTA", "Salida por venta"),
                            ("MERMA", "Merma"),
                            ("AJUSTE", "Ajuste autorizado"),
                        ],
                        max_length=12,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                ("motivo", models.CharField(max_length=255)),
                (
                    "saldo_resultante",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_producto_terminado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="produccion.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en", "-id"],
            },
        ),
    ]
