# Generated by Django 5.2.17 on 2026-09-02 17:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "unidades_por_paquete",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "precio_paquete",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquetes",
                        to="produccion.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["producto__nombre", "nombre"],
                "unique_together": {("producto", "nombre")},
            },
        ),
    ]
